- apiGroups:
    - ""
  resources:
    - configmaps
    - persistentvolumeclaims
    - secrets
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - backup.openeverest.io
  resources:
    - backupclasses
    - backupstorages
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - backup.openeverest.io
  resources:
    - backups
    - restores
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - backup.openeverest.io
  resources:
    - backups/status
    - restores/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.openeverest.io
  resources:
    - instances
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.openeverest.io
  resources:
    - instances/finalizers
  verbs:
    - update
- apiGroups:
    - core.openeverest.io
  resources:
    - instances/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - core.openeverest.io
  resources:
    - providers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - monitoring.openeverest.io
  resources:
    - monitoringconfigs
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - pxc.percona.com
  resources:
    - perconaxtradbclusterbackups
    - perconaxtradbclusterrestores
    - perconaxtradbclusters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - pxc.percona.com
  resources:
    - perconaxtradbclusterbackups/status
    - perconaxtradbclusterrestores/status
    - perconaxtradbclusters/status
  verbs:
    - get
- apiGroups:
    - pxc.percona.com
  resources:
    - perconaxtradbclusters/finalizers
  verbs:
    - update
